### PR TITLE
Update part_b.py

### PR DESCRIPTION
**Pull request by WinstonHue88**
Another refine version

### CODE REVIEW

**Comment by ls1955** [comment]
Had Winston run the program with those assertions beforehand to ensure they are working?

**Comment by WinstonHue88** [comment]
Yes, I did.

**Comment by WinstonHue88** [comment]
How to merge PR......

**Comment by ls1955** [comment]
Alright, I will merge it.

**Comment by ls1955** [comment]
Wait, is the Regexp copy and paste from ChatGPT?

**Review by ls1955 — CHANGES_REQUESTED** [review]
Use the old regexp: `r"^RM(\d{1,3},)*\d+(\.\d{2})?$"`

**Review by ls1955 — CHANGES_REQUESTED** [review]
Use the old regexp: `r"^\d+ ([A-Z][a-zA-Z]+\.? )*([a-zA-Z]+\.? )*[a-zA-Z]+\.?$"`

**Comment by ls1955** [comment]
Looks good to me, brb. Gonna merge it, dawg.

**Pull request merged**
